name : auto-pr #workflow 이름

on : 
    push :
        branches :
            - "feature/**" # 적용 브랜치 범위

permissions :
    contents : write        # contents 권한은 저장소의 컨텐츠를 읽고 쓸 수 있는 권한
    pull-requests: write    # pull-requests 권한은 PR을 생성하고 수정할 수 있는 권한

jobs :
    create-pr: 
        runs-on: ubuntu-latest  # 작업 환경 설정, 깃허브 서버에 있는 ubuntu-latest는 최신 우분투 환경에서 실행됨
    
        steps:
            - name: Checkout
              uses: actions/checkout@v4 
              # 깃허브 액션에서 제공하는 checkout 액션을 사용하여 
              # 현재 브랜치의 코드, 커밋 히스토리 등을 가져옴
              # 이걸 안하면 gh pr create 명령어를 실행할 때 현재 브랜치의 코드가 없어서 
              # PR 생성이 실패함
            
            - name: Create PR if not exists
              env: 
                    GITHUB_TOKEN : ${{ secrets.GITHUB_TOKEN}}   
                    # pr 생성을 위해 토큰을 쓴다. secrets를 쓰면 안전하게 토큰을 관리할 수 있음
                    BRANCH_NAME : ${{ github.ref_name }}
                    # github.ref_name은 현재 브랜치 이름을 가져오는 환경 변수
              run: |
                    echo "Current branch: $BRANCH_NAME"

                    if gh pr view "$BRANCH_NAME" --base main > /dev/null 2>&1; then
                        echo "PR already exists"
                        exit 0
                    fi

                    gh pr create \
                        --title "Auto PR: $BRANCH_NAME" \
                        --body "This PR was automatically created from branch $BRANCH_NAME." \
                        --base main \
                        --head "$BRANCH_NAME"
                
                #위 스크립트의 주 내용을 정리하면 이렇다.
                # echo "Current branch: $BRANCH_NAME" : 현재 브랜치 이름을 출력
                # if gh pr view "$BRANCH_NAME" --base main > /dev/null 2>&1; then : 
                # - 현재 브랜치에서 main 브랜치를 기준으로 PR이 존재하는지 확인
                # fi : PR이 존재하면 종료
                # gh pr create : PR 생성 명령어
                # 그 아래로는 PR 제목, 내용, 기준 브랜치(main), 현재 브랜치(head)를 지정